name: Build EXE

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild (Visual Studio Build Tools)
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest'

      - name: NuGet Restore for C++/CLI solution
        run: nuget restore GraphMakerForms.sln

      - name: Build C++/CLI solution with MSBuild
        run: msbuild GraphMakerForms.sln /p:Configuration=Release /m

      - name: Copy all build files to release folder
        shell: pwsh
        run: |
          # Створюємо теку release, якщо її нема
          if (Test-Path release) {
            Remove-Item release -Recurse -Force
          }
          mkdir release

          # Знаходимо папку з Release білдом
          $releaseFolders = Get-ChildItem -Path . -Recurse -Directory -Filter "Release" | 
                           Where-Object { $_.FullName -like "*GraphMakerForms*" }

          if ($releaseFolders.Count -eq 0) {
            Write-Error "НЕМАЄ папки Release для GraphMakerForms"
            exit 1
          }

          # Копіюємо всі файли з першої знайденої Release папки
          $releaseFolder = $releaseFolders | Select-Object -First 1
          Write-Host "Копіюємо файли з: $($releaseFolder.FullName)"
          
          Copy-Item -Path "$($releaseFolder.FullName)\*" -Destination release\ -Recurse -Force
          
          # Виводимо список файлів що були скопійовані
          Write-Host "Файли в release папці:"
          Get-ChildItem -Path release -Recurse | ForEach-Object { Write-Host $_.FullName }

      - name: Upload Release artifact
        uses: actions/upload-artifact@v4
        with:
          name: GraphCalculator-Release
          path: release/
          
