- name: Build C++/CLI solution with MSBuild
  run: msbuild GraphMakerForms.sln /p:Configuration=Release /m

- name: Find all Release folders and copy all files to publish
  shell: pwsh
  run: |
    # Створюємо теку publish (якщо ще не існує)
    if (-not (Test-Path "publish")) { mkdir publish }

    # Знаходимо всі Release-папки (будь-якого рівня вкладеності)
    $releaseDirs = Get-ChildItem -Path GraphMakerForms -Recurse -Directory | Where-Object { $_.Name -eq "Release" }

    if ($releaseDirs.Count -eq 0) {
      Write-Error "Не знайдено жодної папки Release."
      exit 1
    }

    foreach ($dir in $releaseDirs) {
      Write-Host "Копіюємо з: $($dir.FullName)"
      Copy-Item "$($dir.FullName)\*" publish\ -Recurse -Force
    }

- name: Upload artifact
  uses: actions/upload-artifact@v4
  with:
    name: GraphCalculator-Exe
    path: publish/
