name: Build EXE

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup MSBuild (Visual Studio Build Tools)
        uses: microsoft/setup-msbuild@v1.1
        with:
          vs-version: 'latest'

      - name: NuGet Restore for C++/CLI solution
        run: nuget restore GraphMakerForms.sln

      - name: Build C++/CLI solution with MSBuild
        run: msbuild GraphMakerForms.sln /p:Configuration=Release /m

      - name: Copy ALL output files to unified release folder
        shell: pwsh
        run: |
          $outputDir = "release"
          mkdir $outputDir

          # Знайдемо всі вихідні файли з усіх bin\Release папок
          $outputFiles = Get-ChildItem -Path . -Recurse -Include *.exe,*.dll,*.pdb,*.config -Filter * -File |
                         Where-Object { $_.FullName -match '\\bin\\Release\\' }

          foreach ($file in $outputFiles) {
            Copy-Item $file.FullName -Destination $outputDir -Force
          }

      - name: Upload release artifact
        uses: actions/upload-artifact@v4
        with:
          name: GraphCalculator-Release-Files
          path: release/
